source("R/runtime.R")
# Regression: an earlier or failed run must never be silently overwritten.
run <- tempfile()
dir.create(run)
require_new_run(run)
writeLines("previous result", file.path(run, "sentinel.txt"))
expect_error(require_new_run(run))
stopifnot(identical(readLines(file.path(run, "sentinel.txt")), "previous result"))
unlink(run, recursive = TRUE)
cat("PASS: preservation of existing run directories.\n")
